// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workr.Infrastructure.Persistence;

#nullable disable

namespace Workr.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231119112621_ExerciseEquipment")]
    partial class ExerciseEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExercisesId")
                        .HasColumnType("uuid");

                    b.HasKey("EquipmentId", "ExercisesId");

                    b.HasIndex("ExercisesId");

                    b.ToTable("EquipmentExercise");
                });

            modelBuilder.Entity("Workr.Domain.Accessory.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Accessories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("84967d74-50c6-40e5-9199-30d97ff95e8d"),
                            Name = "Kettlebell",
                            Weight = true
                        },
                        new
                        {
                            Id = new Guid("383fb7ac-1f4a-4bf7-9cbb-1cef985c29eb"),
                            Name = "Dumbbell",
                            Weight = true
                        },
                        new
                        {
                            Id = new Guid("001cb876-cdf6-4625-a2f0-2c414f953ef8"),
                            Name = "Barbell",
                            Weight = true
                        },
                        new
                        {
                            Id = new Guid("52d4c2b3-16a1-401d-8679-8a930b067f8c"),
                            Name = "Bar",
                            Weight = false
                        },
                        new
                        {
                            Id = new Guid("1267a8b7-120b-456a-a4f2-f9853338260e"),
                            Name = "Treadmill",
                            Weight = false
                        },
                        new
                        {
                            Id = new Guid("4b1ffdc4-53ff-4ef0-acdf-e4496e3abf82"),
                            Name = "Bike",
                            Weight = false
                        },
                        new
                        {
                            Id = new Guid("af1d8cde-512c-4e8c-87b4-5ef056a71a73"),
                            Name = "JumpRope",
                            Weight = false
                        });
                });

            modelBuilder.Entity("Workr.Domain.Exercise.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ForceType")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<List<string>>("Instructions")
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("SecondaryMuscleGroups")
                        .HasColumnType("text[]");

                    b.Property<string>("TargetMuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Workr.Domain.Workout.Template.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates", (string)null);
                });

            modelBuilder.Entity("Workr.Domain.Workout.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WorkoutPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("Workr.Domain.Workout.WorkoutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.HasOne("Workr.Domain.Accessory.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workr.Domain.Exercise.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workr.Domain.Workout.Template.WorkoutTemplate", b =>
                {
                    b.OwnsMany("Workr.Domain.Workout.Template.WorkoutBlockTemplate", "BlockTemplates", b1 =>
                        {
                            b1.Property<Guid>("WorkoutTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.HasKey("WorkoutTemplateId", "Id");

                            b1.ToTable("WorkoutBlockTemplates", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkoutTemplateId");

                            b1.OwnsMany("Workr.Domain.Workout.Template.WorkoutItemTemplate", "ItemTemplates", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutTemplateId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkoutBlockTemplateId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Comment")
                                        .HasColumnType("text");

                                    b2.Property<Guid>("ExerciseId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer");

                                    b2.HasKey("WorkoutTemplateId", "WorkoutBlockTemplateId", "Id");

                                    b2.HasIndex("ExerciseId");

                                    b2.ToTable("WorkoutItemTemplates", (string)null);

                                    b2.HasOne("Workr.Domain.Exercise.Exercise", "Exercise")
                                        .WithMany()
                                        .HasForeignKey("ExerciseId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutTemplateId", "WorkoutBlockTemplateId");

                                    b2.OwnsMany("Workr.Domain.Workout.Template.WorkoutSetTemplate", "Sets", b3 =>
                                        {
                                            b3.Property<Guid>("WorkoutTemplateId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("WorkoutBlockTemplateId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("WorkoutItemTemplateId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<int>("Reps")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Weight")
                                                .HasColumnType("integer");

                                            b3.HasKey("WorkoutTemplateId", "WorkoutBlockTemplateId", "WorkoutItemTemplateId", "Id");

                                            b3.ToTable("WorkoutSetTemplates", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("WorkoutTemplateId", "WorkoutBlockTemplateId", "WorkoutItemTemplateId");
                                        });

                                    b2.Navigation("Exercise");

                                    b2.Navigation("Sets");
                                });

                            b1.Navigation("ItemTemplates");
                        });

                    b.Navigation("BlockTemplates");
                });

            modelBuilder.Entity("Workr.Domain.Workout.Workout", b =>
                {
                    b.HasOne("Workr.Domain.Workout.WorkoutPlan", null)
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutPlanId");

                    b.OwnsMany("Workr.Domain.Workout.WorkoutBlock", "Blocks", b1 =>
                        {
                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkoutId", "Id");

                            b1.ToTable("WorkoutBlocks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkoutId");

                            b1.OwnsMany("Workr.Domain.Workout.WorkoutItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("WorkoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("WorkoutBlockId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Comment")
                                        .HasColumnType("text");

                                    b2.Property<int>("CurrentSet")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("ExerciseId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("WorkoutId", "WorkoutBlockId", "Id");

                                    b2.HasIndex("ExerciseId");

                                    b2.ToTable("WorkoutItems", (string)null);

                                    b2.HasOne("Workr.Domain.Exercise.Exercise", "Exercise")
                                        .WithMany()
                                        .HasForeignKey("ExerciseId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("WorkoutId", "WorkoutBlockId");

                                    b2.OwnsMany("Workr.Domain.Workout.WorkoutSet", "Sets", b3 =>
                                        {
                                            b3.Property<Guid>("WorkoutId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("WorkoutBlockId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("WorkoutItemId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<int>("Reps")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Weight")
                                                .HasColumnType("integer");

                                            b3.HasKey("WorkoutId", "WorkoutBlockId", "WorkoutItemId", "Id");

                                            b3.ToTable("WorkoutSets", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("WorkoutId", "WorkoutBlockId", "WorkoutItemId");
                                        });

                                    b2.Navigation("Exercise");

                                    b2.Navigation("Sets");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("Workr.Domain.Workout.WorkoutPlan", b =>
                {
                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
