openapi: '3.1.0'
info:
  version: '1.0.0'
  title: 'Workr API'
  description: Create and track workouts

paths:
  /exercises:
    get:
      tags:
        - exercises
      summary: Get all available exercises
      operationId: getExercise
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
    post:
      tags:
        - exercises
      summary: Create a new exercise
      operationId: createExercise
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exercise'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '400':
          description: Bad request 
  /exercises/{exerciseId}:
    parameters:
      - name: exerciseId
        description: The unique identifier of the exercise
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ExerciseId'
    get:
      tags:
        - exercises
      summary: Get exercise by id
      operationId: getExerciseById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '403':
          description: Forbidden
        '404':
          description: Exercise not found
    put:
      tags:
        - exercises
      summary: Update an exercise
      operationId: updateExercise
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '403':
          description: Forbidden
        '404':
          description: Exercise not found
    delete:
      tags:
        - exercises
      summary: Delete exercise
      operationId: deleteExercise
      responses:
        '204':
          description: No content
        '403':
          description: Forbidden
  /gym:
    post:
      tags:
        - gym
      summary: Create a gym
      operationId: createGym
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gym'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gym'
        '400':
          description: Bad request
  /gym/{gymId}:
    parameters:
      - name: gymId
        description: The unique identifier of the gym
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/GymId'
    get:
      tags:
        - gym
      summary: Get gym details
      operationId: getGymById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gym'
        '404':
          description: Gym not found
    put:
      tags:
        - gym
      summary: Update gym details
      operationId: updateGymById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gym'
        '400':
          description: Bad request
        '404':
          description: Gym not found
    delete:
      tags:
        - gym
      summary: Delete gym
      operationId: deleteGymById
      responses:
        '204':
          description: No content
  /gym/{gymId}/members:
    parameters:
      - name: gymId
        description: The unique identifier of the gym
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/GymId'
    get:
      tags:
        - gym
      summary: Get gym members
      operationId: getGymMembers
      responses:
        '200':
          description: OK
  /gym/{gymId}/members/{memberId}:
    parameters:
      - name: gymId
        description: The unique identifier of the gym
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/GymId'
      - name: memberId
        description: The unique identifier of the user
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/UserId'
    get:
      tags:
        - gym
      summary: Get gym member details
      operationId: getGymMemberById
      responses:
        '200':
          description: OK
    put:
      tags:
        - gym
      summary: Add user to gym
      operationId: addUserToGym
      responses:
        '200':
          description: OK
    delete:
      tags:
        - gym
      summary: Remove user from gym
      operationId: removeGymMember
      responses:
        '204':
          description: No content
  /workout:
    get:
      tags:
        - workout
      summary: Get past workouts
      parameters:
        - name: offset
          description: Offset value 
          in: query
          schema:
            type: number
        - name: limit
          description: Number of workouts to query
          in: query
          schema:
            type: number
        - name: status
          description: Status of the workouts
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
    post:
      tags:
        - workout
      summary: Create a new workout
      operationId: createWorkout
      responses:
        '200':
          description: OK
  /workout/{workoutId}:
    parameters:
      - name: workoutId
        description: The unique identifer of a workout
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/WorkoutId'
    get:
      tags:
        - workout
      summary: Get workout by id
      operationId: getWorkoutById
      responses:
        '200':
          description: OK
    put:
      tags:
        - workout
      summary: Update workout
      operationId: updateWorkout
      responses:
        '200':
          description: OK
    delete:
      tags:
        - workout
      summary: Delete workout
      operationId: deleteWorkout
      responses:
        '204':
          description: No content
  /user:
    post:
      tags:
        - users
      summary: Create a new user
      operationId: createUser
      responses:
        '200': 
          description: OK
        '400':
          description: Bad request
  /user/{userId}:
    parameters:
      - name: userId
        description: The unique identifer of a User
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/UserId'
    get:
      tags:
        - users
      summary: Get user details
      operationId: getUserById
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    put:
      tags:
        - users
      summary: Update user
      operationId: updateUser
      responses:
        '200':
          description: OK
        '404':
          description: Not found
    delete:
      tags:
        - users
      summary: Delete user
      operationId: deleteUser
      responses:
        '204':
          description: No content
    
components:
  schemas:
    UserId:
      description: The unique identifier of a user
      type: string
    ExerciseId:
      description: The unique identifier of an exercise
      type: string
    GymId:
      description: The unique identifier of a gym
      type: string
    WorkoutId:
      description: The unique identifier of a workout
      type: string
    Muscle:
      description: Muscles and muscle groups
      type: string
      enum:
        - biceps
        - triceps
    Difficulty:
      description: Difficulty of an exercise or workout
      type: string
      enum:
        - beginner
        - intermediate
        - advanced
    Price:
      description: Represents a price with quantity and currency
      type: object
      properties:
        quantity:
          type: number
        currency:
          type: string
    Exercise:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        description:
          type: string
        instructions:
          type: array
          items: string
        createdBy:
          $ref: '#/components/schemas/UserId'
        targetMuscleGroups:
          type: array
          items:
            $ref: '#/components/schemas/Muscle'
        level:
          $ref: '#/components/schemas/Difficulty'
    Gym:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          $ref: '#/components/schemas/Price'
        members:
          type: array
          items:
            $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string